[package]
name = "ferrum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
ferrum_compiler = "0.0.2"
log = "0.4.20"

