let i = 0
loop {
  if i >= 10 {
    break
  }

  log.info("loop: {i}")

  // ++ not supported in this language
  // i++

  i += 1
}

let i = 0
while i < 10 {
  log.info("while: {i}")
  i += 1
}

for i in 0..10 {
  log.info("for excl: {i}")
}

for i in 0..=10 {
  log.info("for incl: {i}")
}

const x = [1, 2, 3]

for i in x {
  log.info("for in arr: {i}")
}

for (n, i) in x.with_indicies() {
  log.info("for with idx: ({n}, {i})")
}
